FROM debian

RUN apt-get update
# RUN apt-get install ansible
RUN apt-get -y install python-pip
RUN apt-get -y install python-dev
RUN apt-get -y install libffi-dev
RUN pip install ansible

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -yqq install openssh-server

ADD start_sshd.sh /start_sshd.sh
RUN chmod +x /start_sshd.sh

RUN apt-get -y install supervisor
ADD supervisor.conf /etc/supervisor/conf.d/sshd.conf

EXPOSE 22

CMD ["/usr/bin/supervisord", "-n"]
