---
- name: Create nginx location config
  when: "'{{ openslides_instance_mode }}' == 'path'"
  sudo: yes
  sudo_user: root
  template:
    dest: "/etc/nginx/openslides/{{ item }}"
    src: nginx_instance_path.conf.j2
  with_items: "openslides_{{ openslides_instance_id }}.locations"

- name: Create nginx vhost config
  when: "'{{ openslides_instance_mode }}' == 'subdomain_nossl'"
  sudo: yes
  sudo_user: root
  template:
    dest: "/etc/nginx/openslides/{{ item }}"
    src: nginx_instance_subdomain_nossl.conf.j2
  with_items: "openslides_{{ openslides_instance_id }}.conf"

- name: Create nginx vhost config
  when: "'{{ openslides_instance_mode }}' == 'subdomain'"
  sudo: yes
  sudo_user: root
  template:
    dest: "/etc/nginx/openslides/{{ item }}"
    src: nginx_instance_subdomain.conf.j2
  with_items: "openslides_{{ openslides_instance_id }}.conf"

- name: Reload nginx
  sudo: yes
  sudo_user: root
  service:
    name: nginx
    state: reloaded
